# Generated by Django 5.1.1 on 2024-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
        migrations.AddField(
            model_name='gestaoescolar',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
        migrations.AddField(
            model_name='registroescolar',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
    ]
