# Generated by Django 5.1.1 on 2024-10-22 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(help_text='Carga horaria', validators=[django.core.validators.MaxValueValidator(800)], verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(help_text='Selecione o Curso', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='dependencias_app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='name',
            field=models.CharField(help_text='Nome disciplina', max_length=36, verbose_name='Nome da Disciplina'),
        ),
    ]
