# Generated by Django 5.1.1 on 2024-10-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('Integrado', 'Educação de Jovens e Adultos (EMI)'), ('PROEJA', 'Educação de Jovens e Adultos com Ensino Profissionalizante')], help_text='Selecione a modalidade do curso', max_length=20, verbose_name='Modalidade'),
        ),
    ]
