# Generated by Django 5.1.1 on 2024-10-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome_completo',
        ),
    ]
