# Generated by Django 5.1.1 on 2024-10-11 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataNascimento',
            field=models.DateField(blank=True, help_text='Informe a data de nascimento do Aluno', null=True, verbose_name='DataNascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='Informe o número de telefone do aluno', max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
