# Generated by Django 5.1.1 on 2024-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='primeiro_login',
            field=models.BooleanField(default=True),
        ),
    ]
