# Generated by Django 5.0.3 on 2024-10-19 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(help_text='Informe o nome do curso', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Curso'),
        ),
    ]
