# Generated by Django 5.1.1 on 2024-10-26 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Informe o titulo do evento', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Titulo')),
                ('descricao', models.CharField(help_text='Informe a descricao do evento', max_length=300, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descricao')),
                ('data_inicio', models.DateField(help_text='Informe a data inicial do evento', verbose_name='DataInicio')),
                ('data_fim', models.DateField(help_text='Informe a data final do evento', verbose_name='DataFim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
