# Generated by Django 5.1.1 on 2024-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('Integrado', 'Ensino Médio Integrado'), ('ProEJA', 'Educação de Jovens e Adultos com Ensino Profissionalizante')], help_text='Selecione a modalidade do curso', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_calendario',
            field=models.CharField(choices=[('Integrado', 'Ensino Médio Integrado'), ('ProEJA', 'Educação de Jovens e Adultos com Ensino Profissionalizante')], default='Integrado', help_text='Selecione o tipo de calendário para o evento', max_length=9, verbose_name='TipoCalendario'),
        ),
    ]
