# Generated by Django 5.1.1 on 2024-10-21 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(default=None, max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome_completo',
            field=models.CharField(default='teste', max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
