# Generated by Django 5.1.1 on 2024-11-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEncerramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecerFinal', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoEstudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(default='Restinga', max_length=20)),
                ('formaOferta', models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'Ead'), ('Híbrido', 'Hibrido')], max_length=15)),
                ('turno', models.CharField(choices=[('Manhã', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=10)),
                ('semestre_ano', models.CharField(max_length=5)),
                ('parecer_pedagogico', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrimestreRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1º', 'Primeiro'), ('2º', 'Segundo'), ('3º', 'Terceiro'), ('Todos', 'Todos')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='ppt',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_ppt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curso_ppt', to='dependencias_app.curso'),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplina_ppt', to='dependencias_app.disciplina'),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_ppt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='turmaOrigem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_origem', to='dependencias_app.turma'),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='turmaProgressao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_progressao', to='dependencias_app.turma'),
        ),
        migrations.CreateModel(
            name='PED_EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Criada', 'Criada'), ('Plano de Estudos Elaborado', 'Plano Estudos Elaborado'), ('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizado')], default='Criada', max_length=50)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('notaFinal', models.FloatField(default=0)),
                ('situacao', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Em avaliação', 'Em Avaliacao')], default='Em avaliação', max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_ped_emi', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curso_ped_emi', to='dependencias_app.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplina_ped_emi', to='dependencias_app.disciplina')),
                ('form_encerramento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_encerramento_EMI', to='dependencias_app.formencerramento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_ped_emi', to=settings.AUTH_USER_MODEL)),
                ('plano_estudos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plano_estudos_EMI', to='dependencias_app.planoestudos')),
                ('trimestreRec', models.ManyToManyField(to='dependencias_app.trimestrerec')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
