# Generated by Django 5.1.1 on 2024-10-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_aluno_primeiro_login'),
        ('dependencias_app', '0002_usuario_perfil_alter_registroescolar_table'),
    ]

    operations = [
    ]
