# Generated by Django 5.1.1 on 2024-10-22 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_alter_disciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(help_text='Informe a matrícula do Aluno', max_length=10, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Matricula'),
        ),
    ]
