# Generated by Django 5.1.1 on 2024-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Registros Escolares', 'Registros Escolares'), ('Gestão Escolar', 'Gestao Escolar'), ('Coordenador', 'Coordenador')], max_length=100),
        ),
    ]
