# Generated by Django 5.0.3 on 2024-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('INTEGRADO', 'Educação de Jovens e Adultos (EMI)'), ('PROEJA', 'Educação de Jovens e Adultos com Ensino Profissionalizante')], help_text='Selecione a modalidade do curso', max_length=20, verbose_name='Modalidade'),
        ),
    ]
