# Generated by Django 5.1.1 on 2024-10-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_usuario_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEscolar',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dependencias_app.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('dependencias_app.usuario',),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
