# Generated by Django 5.1.1 on 2024-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_calendario',
            field=models.CharField(choices=[('EMI', 'EMI'), ('PROEJA', 'PROEJA')], default='EMI', help_text='Selecione o tipo de calendário para o evento', max_length=6, verbose_name='TipoCalendario'),
        ),
    ]
