# Generated by Django 5.2.5 on 2026-06-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_usuario_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': ()},
        ),
    ]
