# Generated by Django 5.0.6 on 2024-10-02 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0003_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.EmailField(help_text='Informe o e-mail', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(help_text='Informe a matrícula do Servidor', max_length=10, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(help_text='Informe o nome do Servidor', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='perfil',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Registros Escolares', 'Registros Escolares'), ('Gestão Escolar', 'Gestao Escolar'), ('Coordenador', 'Coordenador')], help_text='Informe o perfil', max_length=50, verbose_name='Perfil'),
        ),
    ]
