# Generated by Django 5.2.5 on 2026-06-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0003_usuario_no_default_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
