# Generated by Django 4.2.4 on 2024-10-07 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias_app', '0002_remove_usuario_oi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do curso', max_length=55, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Curso')),
                ('carga_horaria', models.CharField(help_text='Informe a carga horária do curso', max_length=3, verbose_name='Carga Horária')),
                ('modalidade', models.CharField(choices=[('ProEja', 'ProEja'), ('Integrado', 'Integrado')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Informe o nome da disciplina', max_length=55, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.IntegerField(help_text='Informe a carga horária da disciplina', verbose_name='Carga Horária')),
                ('curso', models.ForeignKey(help_text='Selecione o curso da disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='dependencias_app.curso', verbose_name='Curso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
